package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents an Admin user in the hospital management system.
 *
 * <p>This entity is stored in the database and is used to authenticate
 * administrators who have special privileges, such as managing doctors
 * and overseeing the system.</p>
 *
 * <p>Mapped to the "admin" table in the relational database via JPA.</p>
 */
@Entity
public class Admin {

    /**
     * The unique identifier for this admin record.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The username of the admin.
     * This field is required and cannot be null.
     * Used to identify the admin during login.
     */
    @NotNull(message = "username cannot be null")
    private String username;

    /**
     * The password of the admin.
     * This field is required and cannot be null.
     * It is write-only — meaning it will never be included in JSON responses
     * (only accepted when data is sent to the server).
     */
    @NotNull(message = "password cannot be null")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    /**
     * No-argument constructor required by JPA.
     * JPA needs this to create Admin objects when reading from the database.
     */
    public Admin() {
    }

    /**
     * Creates a new Admin with the given username and password.
     *
     * @param username the admin's login username
     * @param password the admin's login password
     */
    public Admin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * Returns the unique ID of this admin.
     *
     * @return the admin's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID of this admin.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the username of this admin.
     *
     * @return the admin's username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username for this admin.
     *
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password of this admin.
     * Note: This is only accessible internally; it is not included in JSON output.
     *
     * @return the admin's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password for this admin.
     *
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }
}
