package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Transient;

import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.time.LocalDateTime;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Represents an Appointment in the hospital management system.
 *
 * <p>An appointment links a {@link Doctor} and a {@link Patient} together
 * at a specific date and time. Each appointment has a status indicating
 * whether it is scheduled (0) or completed (1).</p>
 *
 * <p>This entity is stored in the relational database (MySQL) and mapped
 * via JPA. Certain doctor and patient fields are hidden from the API response
 * to avoid exposing sensitive information.</p>
 */
@Entity
public class Appointment {

    /**
     * The unique identifier for this appointment record.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The doctor assigned to this appointment.
     * This is a Many-to-One relationship: many appointments can belong to one doctor.
     * Sensitive fields like password, email, phone, and availableTimes are hidden from the JSON response.
     */
    @ManyToOne
    @NotNull(message = "Doctor cannot be null")
    @JsonIgnoreProperties({"availableTimes", "password", "email", "phone"})
    private Doctor doctor;

    /**
     * The patient who booked this appointment.
     * This is a Many-to-One relationship: many appointments can belong to one patient.
     * Sensitive fields like password and address are hidden from the JSON response.
     */
    @ManyToOne
    @NotNull(message = "Patient cannot be null")
    @JsonIgnoreProperties({"password", "address"})
    private Patient patient;

    /**
     * The date and time when the appointment is scheduled.
     * Stored as a full timestamp (e.g., 2025-06-15T10:00:00).
     * Cannot be null.
     */
    @NotNull(message = "Appointment time cannot be null")
    private LocalDateTime appointmentTime;

    /**
     * The current status of the appointment.
     * <ul>
     *   <li>0 = Scheduled (upcoming appointment)</li>
     *   <li>1 = Completed (appointment done / prescription issued)</li>
     * </ul>
     * Cannot be null.
     */
    @NotNull(message = "Status cannot be null")
    private int status;

    /**
     * No-argument constructor required by JPA.
     * JPA uses this to create Appointment instances when reading from the database.
     */
    public Appointment() {
    }

    /**
     * Creates a new Appointment with all required details.
     *
     * @param doctor          the doctor for this appointment
     * @param patient         the patient who booked this appointment
     * @param appointmentTime the date and time of the appointment
     * @param status          the status of the appointment (0 = Scheduled, 1 = Completed)
     */
    public Appointment(Doctor doctor, Patient patient, LocalDateTime appointmentTime, int status) {
        this.doctor = doctor;
        this.patient = patient;
        this.appointmentTime = appointmentTime;
        this.status = status;
    }

    /**
     * Returns the end time of the appointment, which is exactly 1 hour after it starts.
     * This field is not stored in the database — it is calculated on the fly.
     *
     * @return the end time of the appointment, or null if appointmentTime is not set
     */
    @Transient
    public LocalDateTime getEndTime() {
        if (appointmentTime == null) return null;
        return appointmentTime.plusHours(1);
    }

    /**
     * Returns only the date portion of the appointment (without the time).
     * This field is not stored in the database — it is derived from appointmentTime.
     *
     * @return the date of the appointment, or null if appointmentTime is not set
     */
    @Transient
    public LocalDate getAppointmentDate() {
        if (appointmentTime == null) return null;
        return appointmentTime.toLocalDate();
    }

    /**
     * Returns only the time portion of the appointment (without the date).
     * This field is not stored in the database — it is derived from appointmentTime.
     *
     * @return the time of the appointment, or null if appointmentTime is not set
     */
    @Transient
    public LocalTime getAppointmentTimeOnly() {
        if (appointmentTime == null) return null;
        return appointmentTime.toLocalTime();
    }

    /**
     * Returns the unique ID of this appointment.
     *
     * @return the appointment's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID of this appointment.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the doctor assigned to this appointment.
     *
     * @return the doctor
     */
    public Doctor getDoctor() {
        return doctor;
    }

    /**
     * Sets the doctor for this appointment.
     *
     * @param doctor the doctor to assign
     */
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    /**
     * Returns the patient who booked this appointment.
     *
     * @return the patient
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the patient for this appointment.
     *
     * @param patient the patient to assign
     */
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    /**
     * Returns the full date and time of this appointment.
     *
     * @return the appointment date and time
     */
    public LocalDateTime getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * Sets the date and time for this appointment.
     *
     * @param appointmentTime the date and time to set
     */
    public void setAppointmentTime(LocalDateTime appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    /**
     * Returns the current status of this appointment.
     * 0 = Scheduled, 1 = Completed.
     *
     * @return the status code
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the status of this appointment.
     * Use 0 for scheduled and 1 for completed.
     *
     * @param status the status code to set
     */
    public void setStatus(int status) {
        this.status = status;
    }
}
