package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.FetchType;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.List;

/**
 * Represents a Doctor in the hospital management system.
 *
 * <p>This entity holds the professional and contact information of a doctor.
 * Doctors can log in, manage their appointment schedule, and issue prescriptions
 * to patients.</p>
 *
 * <p>Stored in the relational database (MySQL) and mapped via JPA.
 * The list of available appointment times is stored as a separate collection
 * in the database and loaded eagerly.</p>
 */
@Entity
public class Doctor {

    /**
     * The unique identifier for this doctor record.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the doctor.
     * Must be between 3 and 100 characters and cannot be null.
     */
    @NotNull(message = "Name cannot be null")
    @Size(min = 3, max = 100, message = "Name must be between 3 and 100 characters")
    private String name;

    /**
     * The medical speciality of the doctor (e.g., Cardiology, Dermatology).
     * Must be between 3 and 50 characters and cannot be null.
     */
    @NotNull(message = "Speciality cannot be null")
    @Size(min = 3, max = 50, message = "Speciality must be between 3 and 50 characters")
    private String speciality;

    /**
     * The email address of the doctor.
     * Must be a valid email format and cannot be null.
     * Used as the login identifier for doctors.
     */
    @NotNull(message = "Email cannot be null")
    @Email(message = "Invalid email format")
    private String email;

    /**
     * The password of the doctor.
     * Must be at least 6 characters long.
     * This is write-only — it will never appear in API responses (JSON output).
     */
    @NotNull(message = "Password cannot be null")
    @Size(min = 6, message = "Password must be at least 6 characters")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    /**
     * The contact phone number of the doctor.
     * Must be exactly 10 digits.
     */
    @NotNull(message = "Phone number cannot be null")
    @Pattern(regexp = "\\d{10}", message = "Phone number must be 10 digits")
    private String phone;

    /**
     * A list of time slots when the doctor is available for appointments.
     * Each slot is stored as a string (e.g., "09:00", "10:00").
     * Loaded eagerly so that the full list is always available when the doctor is fetched.
     * If this list is empty or null, a default 9:00–17:00 schedule is used.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    private List<String> availableTimes;

    /**
     * No-argument constructor required by JPA.
     * JPA uses this to create Doctor instances when loading records from the database.
     */
    public Doctor() {
    }

    /**
     * Creates a new Doctor with all required details.
     *
     * @param name           the doctor's full name
     * @param speciality     the doctor's medical speciality
     * @param email          the doctor's email address (used for login)
     * @param password       the doctor's password
     * @param phone          the doctor's 10-digit phone number
     * @param availableTimes list of time strings showing when the doctor is available
     */
    public Doctor(String name, String speciality, String email, String password, String phone, List<String> availableTimes) {
        this.name = name;
        this.speciality = speciality;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.availableTimes = availableTimes;
    }

    /**
     * Returns the unique ID of this doctor.
     *
     * @return the doctor's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID of this doctor.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of this doctor.
     *
     * @return the doctor's full name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this doctor.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the medical speciality of this doctor.
     *
     * @return the doctor's speciality (e.g., "Cardiology")
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * Sets the medical speciality of this doctor.
     *
     * @param speciality the speciality to set
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * Returns the email address of this doctor.
     *
     * @return the doctor's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of this doctor.
     *
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the password of this doctor.
     * Note: Not exposed in API responses due to write-only access.
     *
     * @return the doctor's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password of this doctor.
     *
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the phone number of this doctor.
     *
     * @return the doctor's 10-digit phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the phone number of this doctor.
     *
     * @param phone the phone number to set (must be 10 digits)
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns the list of available appointment time slots for this doctor.
     * Each entry is a time string like "09:00" or "14:00".
     *
     * @return list of available time strings
     */
    public List<String> getAvailableTimes() {
        return availableTimes;
    }

    /**
     * Sets the list of available appointment time slots for this doctor.
     *
     * @param availableTimes list of time strings to set
     */
    public void setAvailableTimes(List<String> availableTimes) {
        this.availableTimes = availableTimes;
    }
}
