package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a Patient in the hospital management system.
 *
 * <p>This entity holds the personal information of a patient who can
 * register, log in, book appointments, and view their medical records.</p>
 *
 * <p>Stored in the relational database (MySQL) and mapped via JPA.</p>
 */
@Entity
public class Patient {

    /**
     * The unique identifier for the patient record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the patient.
     * Must be between 3 and 100 characters, and cannot be null.
     */
    @NotNull(message = "Name cannot be null")
    @Size(min = 3, max = 100, message = "Name must be between 3 and 100 characters")
    private String name;

    /**
     * The email address of the patient.
     * Must be a valid email format and cannot be null.
     * Used as the login identifier for patients.
     */
    @NotNull(message = "Email cannot be null")
    @Email(message = "Invalid email format")
    private String email;

    /**
     * The password of the patient.
     * Must be at least 6 characters long.
     * This is write-only — it will never appear in JSON responses.
     */
    @NotNull(message = "Password cannot be null")
    @Size(min = 6, message = "Password must be at least 6 characters")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    /**
     * The phone number of the patient.
     * Must be exactly 10 digits (e.g., 9876543210).
     */
    @NotNull(message = "Phone number cannot be null")
    @Pattern(regexp = "\\d{10}", message = "Phone number must be 10 digits")
    private String phone;

    /**
     * The home address of the patient.
     * Cannot exceed 255 characters.
     */
    @NotNull(message = "Address cannot be null")
    @Size(max = 255, message = "Address cannot exceed 255 characters")
    private String address;

    /**
     * No-argument constructor required by JPA.
     * JPA uses this to create Patient instances when loading records from the database.
     */
    public Patient() {
    }

    /**
     * Creates a new Patient with all required details.
     *
     * @param name     the patient's full name
     * @param email    the patient's email address (used for login)
     * @param password the patient's password
     * @param phone    the patient's 10-digit phone number
     * @param address  the patient's home address
     */
    public Patient(String name, String email, String password, String phone, String address) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
    }

    /**
     * Returns the unique ID of this patient.
     *
     * @return the patient's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID of this patient.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of this patient.
     *
     * @return the patient's full name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this patient.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the email address of this patient.
     *
     * @return the patient's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of this patient.
     *
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the password of this patient.
     * Note: Not exposed in API responses due to write-only access.
     *
     * @return the patient's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password for this patient.
     *
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the phone number of this patient.
     *
     * @return the patient's 10-digit phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the phone number of this patient.
     *
     * @param phone the phone number to set (must be 10 digits)
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns the home address of this patient.
     *
     * @return the patient's address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the home address of this patient.
     *
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }
}
