Token Service
This section covers how to generate and validate JWT tokens to authenticate users securely across the application.

Open the TokenService.java file.
Open TokenService.java in IDE

Create a service class to handle JWT token generation, extraction, and validation.

Hint: Add @Component annotation above the class definition.
Declare necessary repositories to be used as private.

Example:

private final AdminRepository adminRepository;
private final DoctorRepository doctorRepository;
private final PatientRepository patientRepository;

Add the following logic:

generateToken: This method generates a JWT token for a given user's identifier.

Parameters

String identifier: The unique identifier for the user — username for Admin, email for Doctor and Patient.
Return Type

String: The generated JWT token
Hint: The method uses Jwts.builder() to create a JWT token. The token includes the user's identifier as the subject, the current date as the issued date, and sets an expiration of 7 days.

extractIdentifier: This method extracts the identifier (subject) from a JWT token.

Parameters

String token: The JWT token from which the identifier is to be extracted
Return Type

String: The identifier extracted from the token
Hint: The method parses the token using Jwts.parser() and extracts the subject (which can be email or username).

validateToken: This method validates the JWT token for a given user type (admin, doctor, or patient).

Parameters

String token: The JWT token to be validated
String user: The type of user (e.g., admin, doctor, patient)
Return Type

boolean:
true if the token is valid for the specified user type.
false if the token is invalid or expired.
Hint: The method extracts the email from the token and checks if a corresponding user exists in the database. The validation checks depend on the provided user type (admin, doctor, or patient).

getSigningKey: This method retrieves the signing key used for JWT token signing.

Parameters

None
Return Type

SecretKey: The key used for signing the JWT
Hint: Uses the secret from the application configuration (application.properties) to generate a signing key using Keys.hmacShaKeyFor().

Additional Hints
generateToken Method

This method is essential for generating a JWT token for authenticated users. The token includes an expiration time of 7 days, which you can adjust based on your application needs.
extractIdentifier Method

This method is useful for extracting the user identifier (email/username) from the JWT token. It allows identifying the user without additional data in the token.
validateToken Method

This method is used to validate the authenticity of the token. It checks if the token belongs to a valid user and whether the user exists in the database based on the user type (admin, doctor, or patient).
getSigningKey Method

This method provides the signing key for the JWT token generation. It ensures that the same key is used for both signing and verifying the token, enhancing security.


package com.project.back_end.services;

public class TokenService {
// 1. **@Component Annotation**
// The @Component annotation marks this class as a Spring component, meaning Spring will manage it as a bean within its application context.
// This allows the class to be injected into other Spring-managed components (like services or controllers) where it's needed.

// 2. **Constructor Injection for Dependencies**
// The constructor injects dependencies for `AdminRepository`, `DoctorRepository`, and `PatientRepository`,
// allowing the service to interact with the database and validate users based on their role (admin, doctor, or patient).
// Constructor injection ensures that the class is initialized with all required dependencies, promoting immutability and making the class testable.

// 3. **getSigningKey Method**
// This method retrieves the HMAC SHA key used to sign JWT tokens.
// It uses the `jwt.secret` value, which is provided from an external source (like application properties).
// The `Keys.hmacShaKeyFor()` method converts the secret key string into a valid `SecretKey` for signing and verification of JWTs.

// 4. **generateToken Method**
// This method generates a JWT token for a user based on their email.
// - The `subject` of the token is set to the user's email, which is used as an identifier.
// - The `issuedAt` is set to the current date and time.
// - The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.
// - The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.
// The method returns the JWT token as a string.

// 5. **extractEmail Method**
// This method extracts the user's email (subject) from the provided JWT token.
// - The token is first verified using the signing key to ensure it hasn’t been tampered with.
// - After verification, the token is parsed, and the subject (which represents the email) is extracted.
// This method allows the application to retrieve the user's identity (email) from the token for further use.

// 6. **validateToken Method**
// This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).
// - It first extracts the email from the token using the `extractEmail()` method.
// - Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository (AdminRepository, DoctorRepository, or PatientRepository)
//   to see if a user with the extracted email exists.
// - If a match is found for the specified user role, it returns true, indicating the token is valid.
// - If the role or user does not exist, it returns false, indicating the token is invalid.
// - The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.
// This ensures secure access control based on the user's role and their existence in the system.


}
